ENVIRONMENT:
    # Endless episode
    MAX_EPISODE_STEPS: 0
SIMULATOR:
  Robot0:
    HEIGHT: 1.5
    RADIUS: 0.1
    SENSORS: ["RGB_SENSOR", 'DEPTH_SENSOR']
    IS_SET_START_STATE: True
    INIT_POSE: [4., 0., 0.] # [x, y, yaw]
    START_POSITION: [6., 0.01, 5.]
    START_ROTATION: [0., 0., 0., 1.]
  Robot1:
    HEIGHT: 1.5
    RADIUS: 0.1
    SENSORS: ["RGB_SENSOR", 'DEPTH_SENSOR']
    IS_SET_START_STATE: True
    INIT_POSE: [4., 2., 0.] # [x, y, yaw]
    START_POSITION: [8., 0.01, 14.]
    START_ROTATION: [0., 0., 0., 1.]
  AGENTS: ['Robot0', 'Robot1']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "VELOCITY_CONTROL"]

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
