ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    HEIGHT: 1.5
    RADIUS: 0.1
    SENSORS: ["RGB_SENSOR", 'DEPTH_SENSOR']
    IS_SET_START_STATE: False
    START_POSITION: [0.2, 0, 0]
    START_ROTATION: [0, 0, 0, 2]
  AGENT_1:
    HEIGHT: 1.5
    RADIUS: 0.1
    SENSORS: ["RGB_SENSOR", 'DEPTH_SENSOR']
    IS_SET_START_STATE: False
    START_POSITION: [0, 0, 0]
    START_ROTATION: [0, 0, 0, 2]
  AGENTS: ['AGENT_0', 'AGENT_1']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
